---
- name: Check whether disable-module candidates exist
  ansible.builtin.command:
    cmd: /usr/sbin/modinfo {{ item }}
  changed_when: false
  failed_when: false
  loop: "{{ kernel_disable_modules | default([], true) }}"
  tags:
    - kernel_config
    - validate

- name: Check whether blacklist-module candidates exist
  ansible.builtin.command:
    cmd: /usr/sbin/modinfo {{ item }}
  changed_when: false
  failed_when: false
  loop: "{{ kernel_blacklist_modules | default([], true) }}"
  tags:
    - kernel_config
    - validate

- name: Check whether autostart-module candidates exist
  ansible.builtin.command:
    cmd: /usr/sbin/modinfo {{ item }}
  changed_when: false
  failed_when: false
  loop: "{{ kernel_autostart_modules | default([], true) }}"
  tags:
    - kernel_config
    - validate

- name: Validate kernel_sysctl entries
  ansible.builtin.assert:
    that:
      - item.name is defined
      - item.name is string
      - item.name | length > 0
      - item.value is defined
      - item.value | string | length > 0
    quiet: true
    fail_msg: Both name and value should be defined.
  loop: "{{ kernel_sysctl | default([], true) }}"
  tags:
    - kernel_config
    - validate

- name: Validate kernel_sysctl_flush_network_routes type
  ansible.builtin.assert:
    that:
      - kernel_sysctl_flush_network_routes is defined
      - kernel_sysctl_flush_network_routes | type_debug == 'bool'
    quiet: true
  tags:
    - kernel_config
    - validate

- name: Validate kernel_udev_sata_link_power_mgmt value
  ansible.builtin.assert:
    that:
      - kernel_udev_sata_link_power_mgmt is string
      - kernel_udev_sata_link_power_mgmt in ['min_power', 'max_performance', 'medium_power', 'med_power_with_dipm']
    quiet: true
  when: kernel_udev_sata_link_power_mgmt is defined
  tags:
    - kernel_config
    - validate

- name: Validate kernel_udev_disable_bluetooth type
  ansible.builtin.assert:
    that:
      - kernel_udev_disable_bluetooth | type_debug == 'bool'
    quiet: true
  when: kernel_udev_disable_bluetooth is defined
  tags:
    - kernel_config
    - validate

- name: Validate kernel_udev_disable_wake_on_lan type
  ansible.builtin.assert:
    that:
      - kernel_udev_disable_wake_on_lan | type_debug == 'bool'
    quiet: true
  when: kernel_udev_disable_wake_on_lan is defined
  tags:
    - kernel_config
    - validate

- name: Validate kernel_udev_usb_autosuspend_devices type
  ansible.builtin.assert:
    that:
      - kernel_udev_usb_autosuspend_devices is iterable
    quiet: true
  when: kernel_udev_usb_autosuspend_devices is defined
  tags:
    - kernel_config
    - validate

- name: Validate kernel_udev_pci_autosuspend_devices type
  ansible.builtin.assert:
    that:
      - kernel_udev_pci_autosuspend_devices is iterable
    quiet: true
  when: kernel_udev_pci_autosuspend_devices is defined
  tags:
    - kernel_config
    - validate

- name: Validate kernel_udev_enable_wlan_powersave type
  ansible.builtin.assert:
    that:
      - kernel_udev_enable_wlan_powersave | type_debug == 'bool'
    quiet: true
  when: kernel_udev_enable_wlan_powersave is defined
  tags:
    - kernel_config
    - validate

- name: Validate kernel_udev_autosuspend_ahci_devices type
  ansible.builtin.assert:
    that:
      - kernel_udev_autosuspend_ahci_devices | type_debug == 'bool'
    quiet: true
  when: kernel_udev_autosuspend_ahci_devices is defined
  tags:
    - kernel_config
    - validate

- name: Validate kernel_udev_autosuspend_scsi_devices type
  ansible.builtin.assert:
    that:
      - kernel_udev_autosuspend_scsi_devices | type_debug == 'bool'
    quiet: true
  when: kernel_udev_autosuspend_scsi_devices is defined
  tags:
    - kernel_config
    - validate
