---
- name: Execute kernel_config role tasks
  tags:
    - kernel_config
  block:
    - name: Validate provided variables and set OS-dependent variables
      ansible.builtin.import_tasks: asserts.yml
      tags:
        - kernel_config
        - validate

    - name: Disable selected kernel modules via modprobe configuration
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/{{ item }}-disabled.conf
        regexp: '^\s*install\s+{{ item }}\s+/bin/true'
        line: install {{ item }} /bin/true
        state: present
        create: true
        owner: root
        group: root
        mode: '0644'
      loop: "{{ kernel_disable_modules | default([]) }}"
      notify: Reload modules
      tags:
        - kernel_config
        - config

    - name: Blacklist selected kernel modules via modprobe configuration
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/{{ item }}-blacklist.conf
        regexp: '^\s*blacklist\s+{{ item }}'
        line: blacklist {{ item }}
        state: present
        create: true
        owner: root
        group: root
        mode: '0644'
      loop: "{{ kernel_blacklist_modules | default([]) }}"
      notify: Reload modules
      tags:
        - kernel_config
        - config

    - name: Autostart selected kernel modules via modules-load configuration
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/{{ item }}.conf
        regexp: '^\s*{{ item }}'
        line: '{{ item }}'
        state: present
        create: true
        owner: root
        group: root
        mode: '0644'
      loop: "{{ kernel_autostart_modules | default([]) }}"
      notify: Reload modules
      tags:
        - kernel_config
        - config

    - name: Refresh apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['pkg_mgr'] == 'apt'
      tags:
        - kernel_config
        - install

    - name: Install procps package on apt-based systems
      ansible.builtin.apt:
        name: '{{ kernel_procps_packages }}'
        state: present
      when: ansible_facts['pkg_mgr'] == 'apt'
      tags:
        - kernel_config
        - install

    - name: Install procps package on rpm-based systems
      ansible.builtin.dnf:
        name: '{{ kernel_procps_packages }}'
        state: present
      when: ansible_facts['pkg_mgr'] in ['yum', 'dnf', 'dnf5']
      tags:
        - kernel_config
        - install

    - name: Force module reload before running sysctl tasks
      ansible.builtin.meta: flush_handlers
      tags:
        - kernel_config
        - service

    - name: Configure sysctl parameters
      ansible.posix.sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        state: present
        ignoreerrors: false
        reload: true
        sysctl_set: true
      loop: "{{ kernel_sysctl | default([]) }}"
      notify: Flush network routes
      tags:
        - kernel_config
        - config

    - name: Perform udev operations
      ansible.builtin.import_tasks: udev.yml
      tags:
        - kernel_config
        - config
