---
- name: Flush network routes
  ansible.posix.sysctl:
    name: '{{ item }}'
    value: '1'
    reload: true
    state: present
    sysctl_set: true
  loop:
    - net.ipv4.route.flush
    - net.ipv6.route.flush
  when:
    - kernel_sysctl_flush_network_routes
    - ansible_facts['virtualization_type'] not in _container_types
  tags:
    - kernel_config
    - service

- name: Reload modules
  ansible.builtin.systemd:
    name: systemd-modules-load.service
    state: restarted
  when:
    - ansible_facts['service_mgr'] == 'systemd'
    - ansible_facts['virtualization_type'] not in _container_types
  tags:
    - kernel_config
    - service

- name: Reload udev rules
  ansible.builtin.command:
    cmd: udevadm control --reload-rules
  changed_when: true
  when: ansible_facts['virtualization_type'] not in _container_types
  listen: Reload udev
  tags:
    - kernel_config
    - service

- name: Trigger udev
  ansible.builtin.command:
    cmd: udevadm trigger
  changed_when: true
  when: ansible_facts['virtualization_type'] not in _container_types
  listen: Reload udev
  tags:
    - kernel_config
    - service
